import { HashMap } from "./HashMap.js";
const test = new HashMap(0.75, 16);

test.set("apple", "red");
test.set("banana", "yellow");
test.set("carrot", "orange");
test.set("dog", "brown");
test.set("elephant", "gray");
test.set("frog", "green");
test.set("grape", "purple");
test.set("hat", "black");
test.set("ice cream", "white");
test.set("jacket", "blue");
test.set("lion", "golden");
test.set("kite", "pink");
test.set("moon", "silver");
test.set("sky", "blue");
test.set("grass", "green");
test.set("favorite color", "green");
test.set("cartoons", "south park");
test.set("favorite number", "233");
test.set("numbers less than 10", "4");
test.set("spouse", "amanda");
test.set("mother", "patricia");
test.set("wife", "amanda");
test.set("child", "lily");
test.set("outside", "grass");
test.set("funny", "lennon");
test.set("foods", "tacos");
test.get("apple");
test.get("spouse");
test.get("cartoons");
test.get("hat");
// test.has("apple", "red");
// test.has("banana", "yellow");
// test.has("carrot", "orange");
// test.has("dog", "brown");
// test.has("elephant", "gray");
// test.has("frog", "green");
// test.has("grape", "purple");
// test.has("hat", "black");
// test.has("ice cream", "white");
// test.has("jacket", "blue");
// test.has("lion", "golden");
// test.has("kite", "pink");
// test.has("moon", "silver");
// test.has("sky", "blue");
// test.has("grass", "green");
// test.has("favorite color", "green");
// test.has("cartoons", "south park");
// test.has("favorite number", "233");
// test.has("numbers less than 10", "4");
// test.has("spouse", "amanda");
// test.has("mother", "patricia");
// test.has("wife", "amanda");
// test.has("child", "lily");
// test.has("outside", "grass");
// test.has("funny", "lennon");
// test.has("foods", "tacos");

test.remove("outside");
test.remove("foods");
console.log(test);
